# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - invalidkaro
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Pinto-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Pinto-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
